/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class adminlogin extends javax.swing.JFrame {

    /**
     * Creates new form adminlogin
     */
    public adminlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adminusername = new javax.swing.JTextField();
        adminlogin = new javax.swing.JButton();
        adminpassword = new javax.swing.JPasswordField();
        adminshowpassword = new javax.swing.JCheckBox();
        adminexit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("ADMIN LOG-IN PAGE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 90, 272, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(730, 180, 61, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(740, 240, 58, 17);

        adminusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminusernameActionPerformed(evt);
            }
        });
        getContentPane().add(adminusername);
        adminusername.setBounds(860, 180, 232, 26);

        adminlogin.setForeground(new java.awt.Color(255, 102, 0));
        adminlogin.setText("LOGIN");
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        getContentPane().add(adminlogin);
        adminlogin.setBounds(860, 330, 81, 29);

        adminpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(adminpassword);
        adminpassword.setBounds(860, 230, 232, 26);

        adminshowpassword.setForeground(new java.awt.Color(255, 102, 0));
        adminshowpassword.setText("Show Password");
        adminshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminshowpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(adminshowpassword);
        adminshowpassword.setBounds(950, 280, 143, 29);

        adminexit.setForeground(new java.awt.Color(255, 102, 0));
        adminexit.setText("EXIT");
        adminexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminexitActionPerformed(evt);
            }
        });
        getContentPane().add(adminexit);
        adminexit.setBounds(1020, 330, 67, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/backgroundforbilss.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, -30, 2000, 1260);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminusernameActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
        // TODO add your handling code here:
        if  (adminusername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out username");
        }
        else if (adminpassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out password");
        }
        else if(adminusername.getText().contains("AdminJulian") && adminpassword.getText().contains("Admin01")){
            JOptionPane.showMessageDialog(null, "Login Successful");
        }
        else if(adminusername.getText().contains("AdminJude") && adminpassword.getText().contains("Admin02")){
            JOptionPane.showMessageDialog(null, "Login Successful");
        }
        else if(adminusername.getText().contains("AdminJerome") && adminpassword.getText().contains("Admin03")){
            JOptionPane.showMessageDialog(null, "Login Successful");
        }
        else if(adminusername.getText().contains("AdminKiro") && adminpassword.getText().contains("Admin04")){
            JOptionPane.showMessageDialog(null, "Login Successful");
        }
        else if(adminusername.getText().contains("AdminDexter") && adminpassword.getText().contains("Admin05")){
            JOptionPane.showMessageDialog(null, "Login Successful");
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong username or password!","Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_adminloginActionPerformed

    private void adminpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpasswordActionPerformed

    private void adminshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminshowpasswordActionPerformed
        // TODO add your handling code here:
        if (adminshowpassword.isSelected()){
            adminpassword.setEchoChar((char)0);
        }
        else {
            adminpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_adminshowpasswordActionPerformed

    private void adminexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminexitActionPerformed
        // TODO add your handling code here:
        MainMenu main = new MainMenu ();
       main.show();
        
        dispose();
    }//GEN-LAST:event_adminexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminexit;
    private javax.swing.JButton adminlogin;
    private javax.swing.JPasswordField adminpassword;
    private javax.swing.JCheckBox adminshowpassword;
    private javax.swing.JTextField adminusername;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
