/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jerome
 */
public class bills extends javax.swing.JFrame {

    /**
     * Creates new form bills
     */
    public bills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customer = new javax.swing.JTextField();
        reciept = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("BILLS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 120, 60));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Reciept Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 110, 20));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 170, 20));

        customer.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 260, 30));

        reciept.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        reciept.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(reciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 260, 30));

        unit.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        unit.setForeground(new java.awt.Color(255, 102, 0));
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });
        getContentPane().add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 260, 30));

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 255));

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane1.setViewportView(txtprint);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 230, 280));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, -1, 30));

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 500, 80, 30));

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 130, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/backgroundforbilss.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2550, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String cid;
double charge, gramount;
int count;

public void print() {
    // Check if the entered ID is correct
    if (!reciept.getText().equals("12345")) {
        JOptionPane.showMessageDialog(null, "Error: Wrong Receipt Number. Please enter the correct ID number.");
        return; // Exit the method if the ID is incorrect
    }

    // Continue with the print logic if the ID is correct
    String RecieptNumber = reciept.getText();
    String CustomerName = customer.getText();
    String Unit = unit.getText();

    txtprint.setText(txtprint.getText() + "\n");
    txtprint.setText(txtprint.getText() + "YOUR ELECTRICITY BILL " + "\n");
    txtprint.setText(txtprint.getText() + "\n");
    txtprint.setText(txtprint.getText() + "Reciept Number : = " + RecieptNumber + " \n");
    txtprint.setText(txtprint.getText() + "Customer Name : = " + CustomerName + " \n");
    txtprint.setText(txtprint.getText() + "Unit : = " + Unit + " \n");
    txtprint.setText(txtprint.getText() + "Amount (TAX included) : = " + gramount + " \n");
    txtprint.setText(txtprint.getText() + "Thank you Come Again \n");
}



    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  String cid = reciept.getText();
int count = Integer.parseInt(unit.getText());

if (cid.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Error: Receipt Number is empty.");
} else if (!cid.equals("12345")) {
    
    JOptionPane.showMessageDialog(null, "Error: Wrong Receipt Number. Please enter the correct ID number.");
    reciept.setText("");
  
} else {
    
    JOptionPane.showMessageDialog(null, "Computing....");
}



       
        
        if(count < 500)
        {
            charge = 1.00;
        }
        else if(count < 500 && count< 600)
        {
            charge = 1.15;
        }
         else if(count < 600 && count< 800)  
        {
            charge = 1.25;
        }
        else{
             charge = 1.30;
         }
        
        gramount = charge * count;
        print();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            txtprint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(bills.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         MainMenu menu = new MainMenu ();
        menu.show();
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reciept;
    private javax.swing.JTextArea txtprint;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
