/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject ;

/**
 *
 * @author Vinz Kiro Masangkay
 */
public class TermsAndConditions extends javax.swing.JFrame {

    /**
     * Creates new form TermsAndConditions
     */
    public TermsAndConditions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel51 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Please read these Terms and Conditions carefully. All contracts that the provider may ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 16, -1, -1));

        jLabel2.setText("enter into from time to time [for the provision of the provider's services] shall be ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 43, -1, -1));

        jLabel3.setText("governed by these Terms and Conditions, and the Provider will ask the customer for");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        jLabel4.setText("the Customer's express written acceptance of these Terms and Conditions before");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 97, -1, -1));

        jLabel5.setText("providing [any such services] to the customer");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 124, -1, -1));

        jLabel6.setText("1. Billing Period:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 162, -1, -1));

        jLabel7.setText("The billing period for electric services shall be [monthly/quarterly] unless otherwise");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 189, -1, -1));

        jLabel8.setText("specified.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 216, -1, -1));

        jLabel9.setText("2. Meter Reading:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 254, -1, -1));

        jLabel10.setText("The electric utility provider reserves the right to conduct regular meter readings to");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 281, -1, -1));

        jLabel11.setText("determine the amount of electricity consumed. ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 308, -1, -1));

        jLabel12.setText("3. Billing Method:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 346, -1, -1));

        jLabel13.setText("Billing shall be based on actual consumption or an agreed-upon estimation method.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 373, -1, -1));

        jLabel14.setText("4. Billing Statements:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 411, -1, -1));

        jLabel15.setText("Customers will receive detailed billing statements, including information on the");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 438, -1, -1));

        jLabel16.setText("billing period, meter readings, rates, charges, and applicable taxes.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 465, -1, -1));

        jLabel17.setText("5. Payment Due Date:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 503, -1, -1));

        jLabel18.setText("Payments are due on or before [insert due date]. Late payments may be subject to");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 530, -1, -1));

        jLabel19.setText("penalties or interest charges.");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 557, -1, -1));

        jLabel20.setText("6. Payment Options:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 595, -1, -1));

        jLabel21.setText("Customers may make payments through various channels, including online payment ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 622, -1, -1));

        jLabel22.setText("systems, bank transfers, check, or other methods specified by the electric utility");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 649, -1, -1));

        jLabel23.setText("provider.");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 670, -1, -1));

        jLabel24.setText("7. Disconnection for Non-Payment:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 708, -1, -1));

        jLabel25.setText("Failure to make timely payments may result in the disconnection of electric services. ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 730, -1, -1));

        jLabel26.setText("Reconnection may be subject to additional fees.");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 757, -1, -1));

        jLabel27.setText("8. Dispute Resolution:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 795, -1, -1));

        jLabel28.setText("In the event of billing disputes, customers must notify the electric utility provider ");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 822, -1, -1));

        jLabel29.setText("within a specified period. Disputes will be investigated and resolved promptly.");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 849, -1, -1));

        jLabel30.setText("9. Rate Changes:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 887, -1, -1));

        jLabel31.setText("The electric utility provider reserves the right to modify rates with prior notice to ");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 914, -1, -1));

        jLabel32.setText("customers, in accordance with applicable laws and regulations.");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 941, -1, -1));

        jLabel33.setText("10. Service Interruptions:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 979, -1, -1));

        jLabel34.setText("The electric utility provider shall not be liable for damages or losses resulting from ");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 1006, -1, -1));

        jLabel35.setText("service interruptions, including but not limited to those caused by maintenance, ");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1033, -1, -1));

        jLabel36.setText("repairs, or unforeseen circumstances.");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1060, -1, -1));

        jLabel37.setText("11. Termination of Service:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1098, -1, -1));

        jLabel38.setText("The electric utility provider reserves the right to terminate services for reasons such ");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1125, -1, -1));

        jLabel39.setText("as non-payment, violation of terms, or fraudulent activities.");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1152, -1, -1));

        jLabel40.setText("12. Confidentiality:");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1190, -1, -1));

        jLabel41.setText("Customer information and billing details will be treated with confidentiality and will ");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1217, -1, -1));

        jLabel42.setText("not be disclosed to third parties without customer consent, except as required by ");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1257, -1, -1));

        jLabel43.setText("law.");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1284, -1, -1));

        jLabel44.setText("13. Force Majeure:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1322, -1, -1));

        jLabel45.setText("The electric utility provider shall not be liable for any failure or delay in performance");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1349, -1, -1));

        jLabel46.setText("due to events beyond its reasonable control, including but not limited to natural ");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1376, -1, -1));

        jLabel47.setText("disasters, acts of God, or government actions.");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1403, -1, -1));

        jLabel48.setText("14. Governing Law:");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1441, -1, -1));

        jLabel49.setText("These terms and conditions shall be governed by and construed in accordance with");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1468, -1, -1));

        jLabel50.setText("the laws of [insert jurisdiction].");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1495, -1, -1));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(710, 260, 560, 510);

        jLabel51.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Everything You Need To Know");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(840, 200, 300, 60);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("ACCEPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(840, 790, 290, 40);

        jLabel52.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("TERMS & CONDITIONS");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(610, 150, 740, 60);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/backgroundforpayment.jpg"))); // NOI18N
        getContentPane().add(jLabel53);
        jLabel53.setBounds(-2220, -30, 4210, 1250);

        jScrollPane3.setViewportView(jScrollPane4);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(800, 260, 728, 468);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         MainMenu menu = new MainMenu ();
        menu.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TermsAndConditions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TermsAndConditions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
